# Site settings
title: Vet Clinic
description: "Demo Web form for pactice Automation Testing"
baseurl: "/demo-vet-clinic-page/" # the subpath of your site, e.g. /blog
url: "https://v-golovatiuk.github.io/demo-vet-clinic-page/" # the name of your domain
logo_url: svg/logo-vet.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Vet Clinic
    hero_description: A responsive Jekyll web page to practise simple Test Automation.

# Contact form
api_token: "a299c88d-bb9a-43c6-9d8b-407d5e7dd995" # Enter API token here

# Contact info
contact:
    phone: +38 044 123 4567
    emergency: +38 044 123 4567
    email: contact@yoursite.com
    address: Kyiv, Ukraine

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
feed: yes

# Footer
copyright: © 2015 DentistSmile - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
